spring:
  application:
    name: academy
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      data-source-properties:
        charSet: UTF-8
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/academy?user=postgres&password=Grozner23

  flyway:
    schemas: public  # Add this line to specify the schema Flyway should use

server:
  port: 8081
